#!/usr/bin/env bash

DS18B20_PIN=12
REMOTE_UNIT=0 # change to 1 if thiis is a remote unit

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

sudo apt update
sudo apt upgrade -y
sudo apt install -y build-essential python-dev python-pip
sudo pip install RPi.GPIO

# Webserver
sudo pip install Flask

# Bluetooth things
sudo apt install libbluetooth-dev
sudo pip install pybluez
sudo echo 'PRETTY_HOSTNAME=thermostat' > /etc/machine-info

# Scheduler
sudo pip install schedule

# Dependencies for the screen
sudo apt install -y python-imaging python-smbus

# i2c setup
sudo apt install -y python-smbus i2c-tools
sudo echo "i2c-dev" >> /etc/modules
if [ -f /boot/config.txt ]; then
    sudo sed -i '/i2c_arm/s/^#//g' /boot/config.txt # uncomment ine with "i2c_arm" in config file
    sudo sed -i '/i2c1/s/^#//g' /boot/config.txt
fi
if [ -f /etc/modprobe.d/raspi-blacklist.conf ]; then
    sudo sed -i '/i2c-bcm2708/s/^/#/g' /etc/modprobe.d/raspi-blacklist.conf
    sudo sed -i '/spi-bcm2708/s/^/#/g' /etc/modprobe.d/raspi-blacklist.conf
fi
sudo adduser pi i2c

# add onewire support for the DS18B20 temperature sensor
sudo echo "#Enable 1-wire support" >> /boot/config.txt
sudo echo "dtoverlay=w1-gpio:gpiopin=$DS18B20_PIN,pullup=0" >> /boot/config.txt

# PWM
sudo pip install wiringpi

pushd $ROOT
git submodule update --init --recursive
pushd python/Adafruit_Python_SSD1306
sudo python setup.py install
popd
popd

# Write systemd file to start on boot
if [ $REMOTE_UNIT -ne 1 ]; then
   sudo cat > /etc/systemd/system/thermostat.service <<EOF
[Unit]
Description=Thermostat
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=/home/pi
ExecStart=$(which python) $ROOT/python/thermster/thermostat.py -w
ExecStop=$(which kill) \$(/usr/bin/pgrep -f 'thermostat.py')

[Install]
WantedBy=multi-user.target
EOF
else
   sudo cat > /etc/systemd/system/thermostat.service <<EOF
[Unit]
Description=Remote thermometer
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=/home/pi
ExecStart=$(which python) $ROOT/python/thermster/remote_thermometer.py
ExecStop=$(which kill) \$(/usr/bin/pgrep -f 'remote_thermometer.py')

[Install]
WantedBy=multi-user.target
EOF
fi
sudo systemctl daemon-reload
sudo systemctl enable thermostat.service

echo "Enabling I2C and 1-wire requires a resboot."
echo "Type 'y [enter]' to reboot now."
read INPUT

if [ $INPUT == 'y' ]; then
    sudo reboot
fi
